### ISSUE TITLE
Mac users

### ISSUE THREAD

**Issue by luizv** [jsgonsette/Wizium#1]
Hello! Great project. I'm trying to learn more about crossword generator algorithms and found your repository and articles. I'm a Mac user and not so experienced with cross platforms.

Do you have any tips about how I could run it on a Mac? At least the python wrapper? I tried cmake, but with no success. Meanwhile I'll keep trying to make it work.

Thank you!

**Comment by jsgonsette** [comment]
Hello,

thank you for your interest. I have absolutely no experience with Mac world but it would indeed be great to make the lib compatible. It should be relatively easy as it should only be a matter of cmake upgrade for the compilation, and a slight update of the python wrapper. Don't hesitate to post your solution if you manage to do it.

**Comment by jsgonsette** [comment]
Thanks for this update.
