### ISSUE TITLE
Can you explain what the heuristic_level does?

### ISSUE THREAD

**Issue by bsugerman** [jsgonsette/Wizium#5]
Can you explain what the `heuristic_level` in `wiz.solver_start` does?

**Comment by jsgonsette** [comment]
Wizium solver is backtracking-based, meaning that it tries as much as it can to fill in the grid, and goes back in case of blockage. When going back, it can choose to just unstack the previous word and try the next one according to the dictionary. Or it can choose to be more aggressive, and unpack more to change words lower in the stack. This has the advantage to better shuffle the letters around the point where the algorithm was stuck. However, this comes at the cost that maybe it will miss potential solutions by doing so. The heuristic level allows changing this behaviour.
