### ISSUE TITLE
Possibly missing instructions to compile on linux

### ISSUE THREAD

**Issue by ohemelaar** [jsgonsette/Wizium#9]
The instructions for linux didn't work for me, when running `make install` I got the following error:
```
Consolidate compiler generated dependencies of target libWizium
[100%] Built target libWizium
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:52 (file):
  file cannot create directory: /usr/local/./../Binaries/Linux.  Maybe need
  administrative privileges.
make: *** [Makefile:100: install] Error 1
```

Apparently there is some prefix that needs to be configured, I got it to work if I run `CMAKE_INSTALL_PREFIX=/path/to/cloned/Wizium/ cmake ../Sources/` at the start of the instructions instead.

I don't know cmake etc. well so I don't know if it's the best way to solve this.

Platform:
- Ubuntu 22.04
- cmake 3.22.1

**Comment by jsgonsette** [comment]
As stated in your error message, this problem is clearly related to some missing administrative privileges that are required to compile in the target directory. Simply chose a directory for which you have writing permission, this should do the trick.
